### ISSUE TITLE
Possibilità di gestire più di un REG

### ISSUE THREAD

**Issue by danner85** [Ingordigia/homeassistant-addon-setecna#12]
Mi complimento per l'ottimo lavoro e mi domandavo, ha previsto la possibilità di controllare più di un REG?
Penso che potrebbe essere una funzione utile.

**Comment by Ingordigia** [comment]
Ciao @danner85, ti ringrazio.
Ho valutato la possibilità di gestirlo lato codice, ma per ora ho preferito mantenre l'implementazione più semplice possibile.
Inoltre ho accesso ad un solo sistema REG quindi non avrei potuto fare test approfonditi.

Le entità che vengono create in HomeAssistant comunque sono tutte prefissate con l'ID del sistema REG a cui sono associate.
Per questo motivo se è necessario gestire più di un sistema REG in parallelo è sufficiente eseguire più istanze di questo container.

N.B. Il supervisor di HomeAssistant non supporta al momento l'esecuzione multipla dello stesso plugin, quindi i container devono essere gestiti esternamente, utilizzando le variabili d'ambiente per differenziare le credenziali di accesso.
