### ISSUE TITLE
Dati diagnostica

### ISSUE THREAD

**Issue by fileman** [Ingordigia/homeassistant-addon-setecna#9]
Complimenti, progetto molto utile per chi ha una TermoReg, nella scheda diagnostica ci sono tutti i dati disponibili o solo alcuni?
Es. il timer degrado della sorgente e la successiva attivazione di una eventuale Opentherm
Grazie

**Comment by Ingordigia** [comment]
Ciao @fileman, grazie per l'interessamento.
Al momento i dati diagnostici che l'addon espone sono solo quelli di cui ho avuto un esigenza diretta nel mio sistema.
Ho letto che il sistema REG supporta OpenTherm, ma al momento non ho modo di testarlo.
Comunque mi hai dato una ottima idea, quella di documentare i valori che l'addon può gestire, sia in sola lettura che in lettura e scrittura.
Grazie

Hi, thanks for your interest.
At the time of writing the diagnostic data exposed by the addon is only what I use in my system.
I've read that the REG system supports OpenTherm, but I have no way to test it at the moment.
However, you gave me the excellent idea of documenting the parameters ​​that the addon can manage.
Thank you

**Comment by fileman** [comment]
Ciao, nel frattempo ho approfondito come funzionano i sensori di HA ed il codice della tua integrazione.
Io ho anche una opentherm e potrei fare test, appena posso ci metto mano.
Sto aspettando che mi arriva l'interfaccia per interrogare i dati in locale senza passare da cloud setecna.
Posso fare dei PR in questo progetto oppure se preferisci tenere separate le due cose lavoramdo sul mio fork, fammi sapere.
In entrambi i casi, grazie a te per la base ;-)

**Comment by Ingordigia** [comment]
Si ottimo, mi farebbe piacere integrare questo addon con altre funzionalità !
Il codice che ho scritto è un po' artigianale quindi se hai dubbi o suggerimenti per migliorarlo apri pure un issue.
Le PR vanno benissimo perchè anch'io ho chiesto di poter installare la scheda per l'accesso locale tramite modbus TCP, poi mi sarei messo a lavorare sul codice.
Grazie

**Comment by fileman** [comment]
VS Code e Container non sono il mio forte, ho visto che c'è la configurazione per un devcontainer ma poi non riesco ad lanciare il debug.
c'è una procedura particolare per eseguire il codice?
Grazie

**Comment by Ingordigia** [comment]
Ti consiglio di fare un pull perchè ho appena aggiunto al devcontainer l'installazione di Golang.

Per lo sviluppo locale devi commentare la riga
`image: "ghcr.io/ingordigia/{arch}-setecna-addon"`
del file `setecna/config.yml`.
In questo modo HA esegue la build del tuo codice locale invece di utilizzare la versione caricata sul container registry di Github.

Poi da VisualStudioCode devi fare `"Terminale"`->`"Esegui Task"` e dal menù a tendina che si apre scegliere `"Start Home Assistant"`

Dopo qualche minuto potrai collegarti all'indirizzo `http://localhost:7123` e seguire la procedura di onboarding.

Finito l'onboarding se ti sposti in `"Impostazioni"`->`"Componenti aggiuntivi"`->`"Raccolta di componeneti aggiuntivi"` avrai la possibilità di installare il plugin Setecna.

D'ora in poi ogni volta che farai una modifica al codice in locale ti basterà premere il tasto `"REBUILD"` per avere il plugin aggiornato disponibile per il test.

Se può aiutare io ho trovato molto utile questa documentazione:
https://developers.home-assistant.io/docs/add-ons/tutorial
